Repository chloeeee210/mini-board, pull requests merged in 2022-12, with the labels that each got.

#9 close issue #7 Post API Controller unit test 및 controller 구현
  backend/package.json
  backend/src/app.module.ts
  backend/src/board/board.controller.spec.ts
  backend/src/board/board.d.ts
  backend/src/board/board.module.ts
  backend/src/board/board.service.ts
  backend/src/board/dto/create-board.dto.ts
  backend/src/board/dto/update-board.dto.ts
  backend/src/board/entities/board.entity.ts
  backend/src/main.ts
  backend/src/post/dto/create-post.dto.ts
  backend/src/post/dto/update-post.dto.ts
  backend/src/post/entities/post.entity.ts
  backend/src/post/post.controller.spec.ts
  backend/src/post/post.controller.ts
  backend/src/post/post.d.ts
  backend/src/post/post.module.ts
  backend/src/post/post.service.spec.ts
  backend/src/post/post.service.ts
Labels: enhancement

#14 close issue #4 User -> Users API 변경 후 Users API setting
  backend/src/app.module.ts
  backend/src/user/dto/create-user.dto.ts
  backend/src/user/dto/update-user.dto.ts
  backend/src/user/entities/user.entity.ts
  backend/src/user/user.controller.spec.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.spec.ts
  backend/src/user/user.service.ts
  backend/src/users/dto/create-user.dto.ts
  backend/src/users/dto/update-user.dto.ts
  backend/src/users/entities/user.entity.ts
  backend/src/users/users.controller.spec.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.spec.ts
  backend/src/users/users.service.ts
Labels: enhancement

#15 TypeOrm set-up
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/data-source.ts
  backend/src/post/entities/post.entity.ts
Labels: enhancement

#21 resolve CORS
  backend/src/main.ts
Labels: bug

#24 Feat be authentication
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/create-auth.dto.ts
  backend/src/auth/dto/login.request.dto.ts
  backend/src/auth/dto/register.requset.dto.ts
  backend/src/auth/dto/update-auth.dto.ts
  backend/src/auth/jwt/jwt.guard.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
Labels: enhancement

#29 authorization 구현
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt/jwt.guard.ts
  backend/src/auth/jwt/jwt.payload.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/users/users.controller.ts
Labels: enhancement

#32 API 문서 수정 && 코드 리뷰 반영하여 함수명 수정
  backend/package.json
  backend/src/post/dto/create-post.dto.ts
  backend/src/post/post.controller.spec.ts
  backend/src/post/post.controller.ts
  backend/src/post/post.d.ts
  backend/src/post/post.respository.ts
  backend/src/post/post.service.spec.ts
  backend/src/post/post.service.ts
Labels: refactor

#36 Refactor be user service
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/common/exceptions/user-not-found.exception.ts.ts
  backend/src/common/exceptions/user-password-not-valid.exception.ts
  backend/src/users/dtos/user-update.dto.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.repository.ts
  backend/src/users/users.service.ts
Labels: refactor
